
---
- name: install nginx and upload page&config
  hosts: PROD
  become: yes

  vars:
    source_webpage_file: ./mywebsite/index.html
    dest_webpage_file: /var/www/html
    source_config_file: ./config/default
    dest_config_file: /etc/nginx/sites-available/

  tasks:
  - name: check os distro
    debug: var=ansible_os_family

  - block:

    - name: add repository
      apt_repository:
        repo: ppa:nginx/stable

    - name: install nginx
      apt: name=nginx state=latest

    - name: Copy page
      copy: src={{ source_webpage_file }} dest={{ dest_webpage_file }} 
    
    - name: Copy config
      copy: src={{ source_config_file }} dest={{ dest_config_file }} 
      notify: restart nginx
    when: ansible_os_family == "Debian"
  handlers:
  - name: restart nginx
    service: name=nginx state=restarted